<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_QTY_icon_minus-06</name>
   <tag></tag>
   <elementGuidId>cb1bc888-c1f1-4f7c-b4dd-af990f9cf7fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-6']/div/div/form/table/tbody/tr[2]/td[4]/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>54997a77-719b-48e6-bd2e-43d54725a04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_minus-06</value>
      <webElementGuid>dabe2aa4-56af-4862-bfb4-3e68f737c8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-6&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[1]/table[@class=&quot;shop_table shop_table_responsive cart&quot;]/tbody[1]/tr[@class=&quot;cart_item&quot;]/td[@class=&quot;product-quantity&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;noo-quantity-attr&quot;]/button[@class=&quot;qty-decrease&quot;]/i[@class=&quot;icon_minus-06&quot;]</value>
      <webElementGuid>a3dd83eb-e7ad-4e01-a6b5-8d309c951805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-6']/div/div/form/table/tbody/tr[2]/td[4]/div/div/button/i</value>
      <webElementGuid>1fdcd697-9265-47a6-8f23-ced8efbd369a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div/button/i</value>
      <webElementGuid>6d14a901-36c3-4899-8b82-67dc35474017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
