<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_We Work All The Holidays_remove-menumo_264d0c</name>
   <tag></tag>
   <elementGuidId>c3452278-a413-4374-9c46-2422566a9f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.remove-menumobile.icon_close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='off-canvas-nav']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7dc4fcf4-59c6-4eac-8fd8-090c83026c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove-menumobile icon_close</value>
      <webElementGuid>daa83845-e9e8-457d-85e7-e7425234434c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;off-canvas-nav&quot;)/div[@class=&quot;off-canvas-header&quot;]/span[@class=&quot;remove-menumobile icon_close&quot;]</value>
      <webElementGuid>bd01f63f-2907-43e7-a43a-8a6b46f89654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='off-canvas-nav']/div/span</value>
      <webElementGuid>0c34523c-0652-42f5-a34c-fceabfa87922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span</value>
      <webElementGuid>26b57b7e-460e-4767-81cd-0df5ae7698e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
