<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_last_name</name>
   <tag></tag>
   <elementGuidId>997fa0e1-96a1-4593-80b2-5fbe4eca2892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09ce1a58-9d18-45da-bd02-15b057f63370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eaa02e86-cd08-4e53-9502-24949159e99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>94a8ec22-c090-4bae-bb38-43220bc82e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>e007cd01-4760-49d7-8dce-4ab3a44a953d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>a5013a8e-ba62-401d-84dc-699a2c3138cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ramadhany</value>
      <webElementGuid>b207e0e3-d3fb-409f-ab1b-207956963bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>df588705-cccc-41ba-b426-1bf559cce198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_last_name&quot;)</value>
      <webElementGuid>99b2a599-b8dd-41da-b21f-91a9c50887d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_last_name']</value>
      <webElementGuid>0d8cb4ee-fabc-4039-aee6-2582ea2858ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_last_name_field']/span/input</value>
      <webElementGuid>76370f2a-0bb4-48df-8127-134a1a56b4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span/input</value>
      <webElementGuid>59a35019-2fa9-4466-9a82-ee3962a279a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_last_name' and @id = 'billing_last_name']</value>
      <webElementGuid>61816d9f-4c5a-4e31-9ba2-aed80c246d91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
