<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_privacy policy_terms</name>
   <tag></tag>
   <elementGuidId>05cfe58b-9331-4eaf-b453-8a0d436b6d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6f1f805-b7bb-495a-a050-b8938d2e7b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cf0ac018-e570-4825-b849-e7ed47227bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox input-checkbox</value>
      <webElementGuid>b28087f9-b2dd-4833-b635-78a50a590369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>1ad3742c-e945-4263-ae74-def1feb5eeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>4d721c2f-7409-4897-986e-1d2ff954fc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)</value>
      <webElementGuid>fc4654e2-d02d-4ea0-8473-fb102679e74c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms']</value>
      <webElementGuid>2b655e9a-d3e0-4dee-bff8-886f80976d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/div/p/label/input</value>
      <webElementGuid>47d60139-2f8b-4d12-88b2-4f986dc3c07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>b4718d95-263f-4a77-aa78-b8c42bb9cd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'terms' and @id = 'terms']</value>
      <webElementGuid>aefbcca0-e3fb-4818-bee7-713f44aeb218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
