<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rememberme</name>
   <tag></tag>
   <elementGuidId>41dd8199-0454-4c94-a5f1-ad5ee4f15c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0112c10c-1e0b-486a-96df-c059f165b1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox</value>
      <webElementGuid>a75763ac-afbf-4ae1-8b23-573e443d70e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberme</value>
      <webElementGuid>61414c6b-90e6-4d18-abbf-fba4d17b4457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>740f5122-d28a-495b-8313-f04e646c0619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberme</value>
      <webElementGuid>7d06169b-19e9-4dce-8198-aac0f5f80fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>forever</value>
      <webElementGuid>7575018b-6f4d-44d4-8f65-7df9a00feed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberme&quot;)</value>
      <webElementGuid>3f7e4318-5c16-467b-a388-491476bcfc8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberme']</value>
      <webElementGuid>3154ce80-2605-4872-8f50-71f69680b745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div/form/p[3]/label/input</value>
      <webElementGuid>bae6aaf5-28cf-4e04-adc3-2c109d77b223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>bee00e8b-b449-4a8c-b7db-d87da804546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rememberme' and @type = 'checkbox' and @id = 'rememberme']</value>
      <webElementGuid>6adceb39-22ac-4cd0-a6db-21f3d4f40463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
