<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_city</name>
   <tag></tag>
   <elementGuidId>c63b1681-3387-440c-b445-4dcd25821d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae4b5bb3-57b0-498c-9c70-6abe34fdba02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61e58301-6ccd-4c80-8530-a140ba288ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>c73d15d2-4ca9-466e-b4ec-4a361f825a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_city</value>
      <webElementGuid>ddb94b1b-2dba-4d4a-89ac-a54c12ad3520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_city</value>
      <webElementGuid>88855076-b84b-44ca-8947-4dc19c8c8574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level2</value>
      <webElementGuid>b105d733-a78d-47d8-96f7-6b2a68fc3d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_city&quot;)</value>
      <webElementGuid>7a4208df-30ad-4344-8bd4-71237c284423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_city']</value>
      <webElementGuid>3ed72518-e861-4955-9489-b6469b73b6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_city_field']/span/input</value>
      <webElementGuid>fb2cf972-17d7-45ea-aad7-60823cd7cd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/span/input</value>
      <webElementGuid>ff8508fb-ad86-4db9-9229-ae98543683f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_city' and @id = 'billing_city']</value>
      <webElementGuid>12a284fe-ba1f-4930-b482-775a3f92c886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
