<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Checkout_custom-logo</name>
   <tag></tag>
   <elementGuidId>a100592c-e807-4cb4-a93a-ce2febc607ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.custom-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noo-site']/header/div[2]/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91685010-a4d0-4d56-91d0-6c89a3f76aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>248</value>
      <webElementGuid>e1a015a1-df55-4160-8b82-16bf3011f466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>da3cb01e-79f3-44c8-867b-a9273afd05e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.demoqa.com/wp-content/uploads/2019/04/cropped-SHOP-1.png</value>
      <webElementGuid>3ec1fe04-e813-4d0c-bee7-95ad4f2534b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-logo</value>
      <webElementGuid>fd2729ad-64a2-4a3e-8f55-4b853a01bb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ToolsQA Demo Site</value>
      <webElementGuid>9f77cfb2-cb81-485f-be8e-2f42c32c041a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>fde76cf5-7b4d-44f1-8976-8dd355fba5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/header[@class=&quot;noo-header fixed_top header-2&quot;]/div[@class=&quot;navbar-wrapper&quot;]/div[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;noo-container&quot;]/div[@class=&quot;noo-navbar-header&quot;]/div[@class=&quot;navbar-logo&quot;]/a[@class=&quot;custom-logo-link&quot;]/img[@class=&quot;custom-logo&quot;]</value>
      <webElementGuid>9045a3a6-4e2b-43a9-8576-b29e6e638023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/header/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>6863117c-6d4d-4ad0-ad27-db580d9146ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ToolsQA Demo Site']</value>
      <webElementGuid>6111ac16-818d-4cff-9f3b-fa42d4a0eb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9bbd3504-ab7c-4164-8eb8-6873d9d878a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://shop.demoqa.com/wp-content/uploads/2019/04/cropped-SHOP-1.png' and @alt = 'ToolsQA Demo Site']</value>
      <webElementGuid>9ccded6b-4993-425e-8dcd-79baba457af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
